ALTER TABLE usuario 
MODIFY COLUMN data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE usuario 
ADD COLUMN data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
ON UPDATE CURRENT_TIMESTAMP;
