CREATE TABLE editora(
  id_editora INT PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(255) UNIQUE NOT NULL,
  cidade VARCHAR(64),
  estado VARCHAR(64),
  pais VARCHAR(64),
  data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
