CREATE TABLE categoria(
  id_categoria INT PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(128) NOT NULL UNIQUE,
  descricao TEXT,
  data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
